# Generated by Django 5.2.12 on 2026-03-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('double', '2 Share'), ('triple', '3 Share'), ('four', '4 Share'), ('five', '5 Share'), ('six', '6 Share')], max_length=20),
        ),
    ]
