# Generated by Django 5.2.12 on 2026-03-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hostel_amenities_alter_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='rooms_per_floor',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hostel',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='total_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
