# Generated by Django 5.2.12 on 2026-03-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hostel_rooms_per_floor_hostel_total_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='floor_room_counts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
