# Generated by Django 5.2.12 on 2026-03-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hostel_floor_room_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelphoto',
            name='url',
            field=models.TextField(),
        ),
    ]
