# Generated by Django 5.2.12 on 2026-03-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_hostelphoto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='student_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
