# Generated by Django 5.2.12 on 2026-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_room_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
