# Generated by Django 5.2.12 on 2026-03-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_room_booking_advance_room_security_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='pending_update',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
